spring.application.name=universiry-backend
spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}
server.error.include-message=never

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/universiry_dev}
spring.datasource.username=${DB_USERNAME:universiry_dev}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
